### PR TITLE
Update feature-manually-handling-sharding-ddl-locks.md

### PR DESCRIPTION
**Pull request by zoujia-cm**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-dm) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)
change show-dd-locks to show-ddl-locks

### Which DM version(s) do your changes apply to? (Required)

- [ ] master (the latest development version, including v3.0 changes)
- [ ] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by CharLotteiu** [comment]
Seems like this PR is exactly the same as https://github.com/pingcap/docs-dm/pull/596. If it is a misoperation, I will close this PR. @zoujia-cm

**Comment by zoujia-cm** [comment]
> Seems like this PR is exactly the same as #596. If it is a misoperation, I will close this PR. @zoujia-cm

in #596, "unlockd-dll-lock" is at line 272. in #597 "show-dd-lock" is at line 304.they are different.

**Pull request merged**
