### PR TITLE
zh,en: update dmctl commands for v2.0.3

### PR DESCRIPTION
**Pull request by GMHDBJD**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-dm) that's required for repo owners to accept my contribution.

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v3.0 changes)
- [x] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by lance6716** [comment]
will this pr be merged now or after 2.0.3

**Comment by GMHDBJD** [comment]
Maybe after 2.0.3 release will be better

**Comment by CharLotteiu** [comment]
Does this PR still work in progress? Seems like the `Git Commit Hash` is not a value.

**Comment by lance6716** [comment]
> Does this PR still work in progress? Seems like the `Git Commit Hash` is not a value.

author says he wants to left these fields as templates

/lgtm

**Pull request merged**
