### PR TITLE
faq: update dm docs and faq (#551)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #551 to release-1.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs-dm repo:
git pr https://github.com/pingcap/docs-dm/pull/554
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs-dm.git pr/554:release-1.0-d46a60321f96
```

---

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-dm) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)
Update dm docs and faq.

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v3.0 changes)
- [x] v2.0 (TiDB DM 2.0 versions)
- [x] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by CharLotteiu** [comment]
Seems like the release-1.0 branch doesn't have the `zh/dmctl-introduction.md` and `zh/source-configuration-file.md` before. Do we need these two files here? @lance6716

**Comment by lance6716** [comment]
@CharLotteiu "source" conception in `zh/source-configuration-file.md` is 2.0 only, and changes of `zh/dmctl-introduction.md` seems only involving new commands which introduced in 2.0, so I recommended close this PR

**Comment by CharLotteiu** [comment]
> @CharLotteiu "source" conception in `zh/source-configuration-file.md` is 2.0 only, and changes of `zh/dmctl-introduction.md` seems only involving new commands which introduced in 2.0, so I recommended close this PR

What about the FAQ file? Anything that release-1.0 needs?

**Comment by lance6716** [comment]
> > @CharLotteiu "source" conception in `zh/source-configuration-file.md` is 2.0 only, and changes of `zh/dmctl-introduction.md` seems only involving new commands which introduced in 2.0, so I recommended close this PR
> 
> What about the FAQ file? Anything that release-1.0 needs?

not related to 1.0, or architecture of DM 1.0 won't meet that problem

**Comment by CharLotteiu** [comment]
Closed as the content is not related to DM 1.0

**Pull request closed without merging**
