### PR TITLE
en: fix wrong section number

### PR DESCRIPTION
**Pull request by lance6716**
### What is changed, added or deleted? (Required)
fix wrong section number

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v2.0 changes for now)
- [x] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by lance6716** [comment]
> LGTM. Should we also change it in master?

OK, please edit label for me, I don't have permission

**Comment by GMHDBJD** [comment]
> OK, please edit label for me, I don't have permission

No cherry-pick 2.0 Label. You may need to manualy cherrypick it after merged.

**Pull request merged**
