### PR TITLE
[2.0.2] en: add two keepalive config in worker config file (#580)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #580 to release-2.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs-dm repo:
git pr https://github.com/pingcap/docs-dm/pull/592
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs-dm.git pr/592:release-2.0-8105684d83b6
```

---

### What is changed, added, or deleted? (Required)

Add two keepalive config in worker config file.

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v3.0 changes)
- [x] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-dm/pull/567
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by qiancai — COMMENTED** [review]
/lgtm

**Review by CharLotteiu — APPROVED** [review]

**Pull request merged**
