### PR TITLE
[2.0.2] zh: add an alerting rule (#569)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #569 to release-2.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs-dm repo:
git pr https://github.com/pingcap/docs-dm/pull/585
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs-dm.git pr/585:release-2.0-7f9260244f2a
```

---

### What is changed, added, or deleted? (Required)

align with https://github.com/pingcap/dm/pull/1438

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v3.0 changes)
- [x] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by CharLotteiu — APPROVED** [review]

**Review by GMHDBJD — COMMENTED** [review]
/lgtm

**Pull request merged**
