### PR TITLE
add `operate-source show`

### PR DESCRIPTION
**Pull request by lance6716**
### What is changed, added or deleted? (Required)

add `operate-source show`

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v2.0 changes for now)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/dm/pull/838

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by TomShawn** [comment]
@lance6716 Is this PR only applicable to `master`?

**Comment by lance6716** [comment]
> @lance6716 Is this PR only applicable to `master`?

yes. "source" is a new concept introduced in v2.0

**Pull request merged**
