### PR TITLE
update notes for dmctl

### PR DESCRIPTION
**Pull request by Joyinqin**
### What is changed, added or deleted? (Required)
add notes to clarify https://github.com/pingcap/dm/issues/885

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v2.0 changes for now)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-dm/pull/221
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by lance6716** [comment]
maybe could align with #258

**Comment by lance6716** [comment]
LGTM

**Review by lilin90 — APPROVED** [review]
LGTM

**Pull request merged**
