### PR TITLE
zh: fix testdm-task.yaml format

### PR DESCRIPTION
**Pull request by jerrylisl**
fix testdm-task.yaml format in quick-start-with-dm.md

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-dm) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)

fix the format of testdm-task.yaml to ensure the related command work

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v3.0 changes)
- [x] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by Liuxiaozhen12** [comment]
status/PTAL

**Review by lance6716 — APPROVED** [review]
this is caused by GitHub will adjust some indentation when pasting, very annoying

**Comment by lance6716** [comment]
Thanks for fixing it @jerrylisl

**Review by CharLotteiu — APPROVED** [review]

**Pull request merged**
