### PR TITLE
*: update tidb-server download URL

### PR DESCRIPTION
**Pull request by lance6716**
### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v3.0 changes)
- [x] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): some comments from https://github.com/pingcap/dm/issues/1431

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by CharLotteiu — APPROVED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
/lgtm

**Pull request merged**
