### PR TITLE
en: fix wrong section number (#147)

### PR DESCRIPTION
**Pull request by lance6716**
### What is changed, added or deleted? (Required)

manually cherry-pick #147 

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v2.0 changes for now)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by TomShawn** [comment]
lgtm

**Comment by toutdesuite** [comment]
unlabel translation/doing

**Pull request merged**
